name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: steinvenior
        password: ${{ secrets.KEY }}
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file .docker/Dockerfile --tag my-image-name:$(date +%s)
